// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Text;
    using Coherence;
    using Coherence.Brisk;
    using Coherence.ProtocolDef;
    using Coherence.Connection;
    using Coherence.Entities;
    using System.Collections.Generic;
    using Coherence.SimulationFrame;
    using Coherence.Core;

    public class ComponentInteropHandler : IComponentInteropHandler
    {
        public unsafe ICoherenceComponentData GetComponent(UInt32 type, IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            switch(type)
            {
                case 0: return WorldPosition.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 1: return WorldOrientation.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 2: return LocalUserComponent.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 3: return WorldPositionQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 4: return ArchetypeComponent.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 5: return Persistence.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 6: return ConnectedEntity.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 7: return UniqueID.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 8: return Connection.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 9: return ConnectionScene.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 10: return Global.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 11: return GlobalQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 12: return Tag.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 13: return TagQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 14: return PreserveChildren.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 15: return Scene.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 16: return AssetId.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 17: return GenericScale.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 18: return GenericFieldInt0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 19: return GenericFieldInt1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 20: return GenericFieldInt2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 21: return GenericFieldInt3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 22: return GenericFieldInt4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 23: return GenericFieldInt5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 24: return GenericFieldInt6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 25: return GenericFieldInt7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 26: return GenericFieldInt8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 27: return GenericFieldInt9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 28: return GenericFieldUInt0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 29: return GenericFieldUInt1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 30: return GenericFieldUInt2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 31: return GenericFieldUInt3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 32: return GenericFieldUInt4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 33: return GenericFieldUInt5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 34: return GenericFieldUInt6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 35: return GenericFieldUInt7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 36: return GenericFieldUInt8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 37: return GenericFieldUInt9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 38: return GenericFieldBool0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 39: return GenericFieldBool1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 40: return GenericFieldBool2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 41: return GenericFieldBool3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 42: return GenericFieldBool4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 43: return GenericFieldBool5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 44: return GenericFieldBool6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 45: return GenericFieldBool7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 46: return GenericFieldBool8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 47: return GenericFieldBool9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 48: return GenericFieldFloat0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 49: return GenericFieldFloat1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 50: return GenericFieldFloat2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 51: return GenericFieldFloat3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 52: return GenericFieldFloat4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 53: return GenericFieldFloat5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 54: return GenericFieldFloat6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 55: return GenericFieldFloat7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 56: return GenericFieldFloat8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 57: return GenericFieldFloat9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 58: return GenericFieldDouble0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 59: return GenericFieldDouble1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 60: return GenericFieldDouble2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 61: return GenericFieldDouble3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 62: return GenericFieldDouble4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 63: return GenericFieldDouble5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 64: return GenericFieldDouble6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 65: return GenericFieldDouble7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 66: return GenericFieldDouble8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 67: return GenericFieldDouble9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 68: return GenericFieldVector0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 69: return GenericFieldVector1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 70: return GenericFieldVector2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 71: return GenericFieldVector3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 72: return GenericField2dVector0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 73: return GenericField2dVector1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 74: return GenericField2dVector2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 75: return GenericField2dVector3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 76: return GenericFieldString0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 77: return GenericFieldString1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 78: return GenericFieldString2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 79: return GenericFieldString3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 80: return GenericFieldString4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 81: return GenericFieldQuaternion0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 82: return GenericFieldEntity0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 83: return GenericFieldEntity1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 84: return GenericFieldEntity2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 85: return GenericFieldEntity3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 86: return GenericFieldEntity4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 87: return GenericFieldEntity5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 88: return GenericFieldEntity6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 89: return GenericFieldEntity7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 90: return GenericFieldEntity8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 91: return GenericFieldEntity9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 92: return GenericFieldBytes0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 93: return GenericFieldByte0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 94: return GenericFieldByte1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 95: return GenericFieldByte2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 96: return GenericFieldByte3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 97: return GenericFieldByte4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 98: return GenericFieldByte5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 99: return GenericFieldByte6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 100: return GenericFieldByte7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 101: return GenericFieldByte8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 102: return GenericFieldByte9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 103: return GenericFieldSByte0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 104: return GenericFieldSByte1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 105: return GenericFieldSByte2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 106: return GenericFieldSByte3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 107: return GenericFieldSByte4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 108: return GenericFieldSByte5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 109: return GenericFieldSByte6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 110: return GenericFieldSByte7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 111: return GenericFieldSByte8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 112: return GenericFieldSByte9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 113: return GenericFieldShort0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 114: return GenericFieldShort1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 115: return GenericFieldShort2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 116: return GenericFieldShort3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 117: return GenericFieldShort4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 118: return GenericFieldShort5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 119: return GenericFieldShort6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 120: return GenericFieldShort7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 121: return GenericFieldShort8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 122: return GenericFieldShort9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 123: return GenericFieldUShort0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 124: return GenericFieldUShort1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 125: return GenericFieldUShort2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 126: return GenericFieldUShort3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 127: return GenericFieldUShort4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 128: return GenericFieldUShort5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 129: return GenericFieldUShort6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 130: return GenericFieldUShort7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 131: return GenericFieldUShort8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 132: return GenericFieldUShort9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 133: return GenericFieldChar0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 134: return GenericFieldChar1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 135: return GenericFieldChar2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 136: return GenericFieldChar3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 137: return GenericFieldChar4.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 138: return GenericFieldChar5.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 139: return GenericFieldChar6.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 140: return GenericFieldChar7.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 141: return GenericFieldChar8.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 142: return GenericFieldChar9.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 143: return GenericFieldLong0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 144: return GenericFieldLong1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 145: return GenericFieldLong2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 146: return GenericFieldLong3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 147: return GenericFieldULong0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 148: return GenericFieldULong1.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 149: return GenericFieldULong2.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 150: return GenericFieldULong3.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 151: return GenericFieldColor0.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 152: return GenericFieldColor1.FromInterop(data, dataSize, simFrames, simFramesCount);
            }

            throw new ArgumentException($"Unkown component type {type}", nameof(type));
        }

        public unsafe void UpdateComponent(CoherenceCore core, InteropEntity entity, ICoherenceComponentData component)
        {
            var componentType = component.GetComponentType();
            var frames = component.GetSimulationFrames();

            switch (componentType)
            {
                case 0:
                {
                    var orig = (WorldPosition)component;
                    var val = new WorldPosition.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 1:
                {
                    var orig = (WorldOrientation)component;
                    var val = new WorldOrientation.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 2:
                {
                    var orig = (LocalUserComponent)component;
                    var val = new LocalUserComponent.Interop();

                    val.localIndex = orig.localIndex;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 3:
                {
                    var orig = (WorldPositionQuery)component;
                    var val = new WorldPositionQuery.Interop();

                    val.position = orig.position;
                    val.radius = orig.radius;

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 4:
                {
                    var orig = (ArchetypeComponent)component;
                    var val = new ArchetypeComponent.Interop();

                    val.index = orig.index;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 5:
                {
                    var orig = (Persistence)component;
                    var val = new Persistence.Interop();


                    core.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 6:
                {
                    var orig = (ConnectedEntity)component;
                    var val = new ConnectedEntity.Interop();

                    val.value = orig.value;
                    val.pos = orig.pos;
                    val.rot = orig.rot;
                    val.scale = orig.scale;

                    core.UpdateComponent(entity, componentType, val, 44, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 7:
                {
                    var orig = (UniqueID)component;
                    var val = new UniqueID.Interop();

                    var pinneduuid = orig.uuid != null ? Encoding.UTF8.GetBytes(orig.uuid) : null; fixed (void* pinnedPtruuid = pinneduuid) { val.uuid = new ByteArray { Data = pinnedPtruuid, Length =  pinneduuid?.Length ?? 0 };

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 8:
                {
                    var orig = (Connection)component;
                    var val = new Connection.Interop();

                    val.id = orig.id;
                    val.type = orig.type;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 9:
                {
                    var orig = (ConnectionScene)component;
                    var val = new ConnectionScene.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 10:
                {
                    var orig = (Global)component;
                    var val = new Global.Interop();


                    core.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 11:
                {
                    var orig = (GlobalQuery)component;
                    var val = new GlobalQuery.Interop();


                    core.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 12:
                {
                    var orig = (Tag)component;
                    var val = new Tag.Interop();

                    var pinnedtag = orig.tag != null ? Encoding.UTF8.GetBytes(orig.tag) : null; fixed (void* pinnedPtrtag = pinnedtag) { val.tag = new ByteArray { Data = pinnedPtrtag, Length =  pinnedtag?.Length ?? 0 };

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 13:
                {
                    var orig = (TagQuery)component;
                    var val = new TagQuery.Interop();

                    var pinnedtag = orig.tag != null ? Encoding.UTF8.GetBytes(orig.tag) : null; fixed (void* pinnedPtrtag = pinnedtag) { val.tag = new ByteArray { Data = pinnedPtrtag, Length =  pinnedtag?.Length ?? 0 };

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 14:
                {
                    var orig = (PreserveChildren)component;
                    var val = new PreserveChildren.Interop();


                    core.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 15:
                {
                    var orig = (Scene)component;
                    var val = new Scene.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 16:
                {
                    var orig = (AssetId)component;
                    var val = new AssetId.Interop();

                    var pinnedvalue = orig.value != null ? Encoding.UTF8.GetBytes(orig.value) : null; fixed (void* pinnedPtrvalue = pinnedvalue) { val.value = new ByteArray { Data = pinnedPtrvalue, Length =  pinnedvalue?.Length ?? 0 };
                    val.isFromGroup = orig.isFromGroup ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 17, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 17:
                {
                    var orig = (GenericScale)component;
                    var val = new GenericScale.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 18:
                {
                    var orig = (GenericFieldInt0)component;
                    var val = new GenericFieldInt0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 19:
                {
                    var orig = (GenericFieldInt1)component;
                    var val = new GenericFieldInt1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 20:
                {
                    var orig = (GenericFieldInt2)component;
                    var val = new GenericFieldInt2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 21:
                {
                    var orig = (GenericFieldInt3)component;
                    var val = new GenericFieldInt3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 22:
                {
                    var orig = (GenericFieldInt4)component;
                    var val = new GenericFieldInt4.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 23:
                {
                    var orig = (GenericFieldInt5)component;
                    var val = new GenericFieldInt5.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 24:
                {
                    var orig = (GenericFieldInt6)component;
                    var val = new GenericFieldInt6.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 25:
                {
                    var orig = (GenericFieldInt7)component;
                    var val = new GenericFieldInt7.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 26:
                {
                    var orig = (GenericFieldInt8)component;
                    var val = new GenericFieldInt8.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 27:
                {
                    var orig = (GenericFieldInt9)component;
                    var val = new GenericFieldInt9.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 28:
                {
                    var orig = (GenericFieldUInt0)component;
                    var val = new GenericFieldUInt0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 29:
                {
                    var orig = (GenericFieldUInt1)component;
                    var val = new GenericFieldUInt1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 30:
                {
                    var orig = (GenericFieldUInt2)component;
                    var val = new GenericFieldUInt2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 31:
                {
                    var orig = (GenericFieldUInt3)component;
                    var val = new GenericFieldUInt3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 32:
                {
                    var orig = (GenericFieldUInt4)component;
                    var val = new GenericFieldUInt4.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 33:
                {
                    var orig = (GenericFieldUInt5)component;
                    var val = new GenericFieldUInt5.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 34:
                {
                    var orig = (GenericFieldUInt6)component;
                    var val = new GenericFieldUInt6.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 35:
                {
                    var orig = (GenericFieldUInt7)component;
                    var val = new GenericFieldUInt7.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 36:
                {
                    var orig = (GenericFieldUInt8)component;
                    var val = new GenericFieldUInt8.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 37:
                {
                    var orig = (GenericFieldUInt9)component;
                    var val = new GenericFieldUInt9.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 38:
                {
                    var orig = (GenericFieldBool0)component;
                    var val = new GenericFieldBool0.Interop();

                    val.number = orig.number ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 39:
                {
                    var orig = (GenericFieldBool1)component;
                    var val = new GenericFieldBool1.Interop();

                    val.number = orig.number ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 40:
                {
                    var orig = (GenericFieldBool2)component;
                    var val = new GenericFieldBool2.Interop();

                    val.number = orig.number ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 41:
                {
                    var orig = (GenericFieldBool3)component;
                    var val = new GenericFieldBool3.Interop();

                    val.number = orig.number ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 42:
                {
                    var orig = (GenericFieldBool4)component;
                    var val = new GenericFieldBool4.Interop();

                    val.number = orig.number ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 43:
                {
                    var orig = (GenericFieldBool5)component;
                    var val = new GenericFieldBool5.Interop();

                    val.number = orig.number ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 44:
                {
                    var orig = (GenericFieldBool6)component;
                    var val = new GenericFieldBool6.Interop();

                    val.number = orig.number ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 45:
                {
                    var orig = (GenericFieldBool7)component;
                    var val = new GenericFieldBool7.Interop();

                    val.number = orig.number ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 46:
                {
                    var orig = (GenericFieldBool8)component;
                    var val = new GenericFieldBool8.Interop();

                    val.number = orig.number ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 47:
                {
                    var orig = (GenericFieldBool9)component;
                    var val = new GenericFieldBool9.Interop();

                    val.number = orig.number ? (System.Byte)1 : (System.Byte)0;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 48:
                {
                    var orig = (GenericFieldFloat0)component;
                    var val = new GenericFieldFloat0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 49:
                {
                    var orig = (GenericFieldFloat1)component;
                    var val = new GenericFieldFloat1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 50:
                {
                    var orig = (GenericFieldFloat2)component;
                    var val = new GenericFieldFloat2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 51:
                {
                    var orig = (GenericFieldFloat3)component;
                    var val = new GenericFieldFloat3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 52:
                {
                    var orig = (GenericFieldFloat4)component;
                    var val = new GenericFieldFloat4.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 53:
                {
                    var orig = (GenericFieldFloat5)component;
                    var val = new GenericFieldFloat5.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 54:
                {
                    var orig = (GenericFieldFloat6)component;
                    var val = new GenericFieldFloat6.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 55:
                {
                    var orig = (GenericFieldFloat7)component;
                    var val = new GenericFieldFloat7.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 56:
                {
                    var orig = (GenericFieldFloat8)component;
                    var val = new GenericFieldFloat8.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 57:
                {
                    var orig = (GenericFieldFloat9)component;
                    var val = new GenericFieldFloat9.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 58:
                {
                    var orig = (GenericFieldDouble0)component;
                    var val = new GenericFieldDouble0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 59:
                {
                    var orig = (GenericFieldDouble1)component;
                    var val = new GenericFieldDouble1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 60:
                {
                    var orig = (GenericFieldDouble2)component;
                    var val = new GenericFieldDouble2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 61:
                {
                    var orig = (GenericFieldDouble3)component;
                    var val = new GenericFieldDouble3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 62:
                {
                    var orig = (GenericFieldDouble4)component;
                    var val = new GenericFieldDouble4.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 63:
                {
                    var orig = (GenericFieldDouble5)component;
                    var val = new GenericFieldDouble5.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 64:
                {
                    var orig = (GenericFieldDouble6)component;
                    var val = new GenericFieldDouble6.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 65:
                {
                    var orig = (GenericFieldDouble7)component;
                    var val = new GenericFieldDouble7.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 66:
                {
                    var orig = (GenericFieldDouble8)component;
                    var val = new GenericFieldDouble8.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 67:
                {
                    var orig = (GenericFieldDouble9)component;
                    var val = new GenericFieldDouble9.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 68:
                {
                    var orig = (GenericFieldVector0)component;
                    var val = new GenericFieldVector0.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 69:
                {
                    var orig = (GenericFieldVector1)component;
                    var val = new GenericFieldVector1.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 70:
                {
                    var orig = (GenericFieldVector2)component;
                    var val = new GenericFieldVector2.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 71:
                {
                    var orig = (GenericFieldVector3)component;
                    var val = new GenericFieldVector3.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 72:
                {
                    var orig = (GenericField2dVector0)component;
                    var val = new GenericField2dVector0.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 73:
                {
                    var orig = (GenericField2dVector1)component;
                    var val = new GenericField2dVector1.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 74:
                {
                    var orig = (GenericField2dVector2)component;
                    var val = new GenericField2dVector2.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 75:
                {
                    var orig = (GenericField2dVector3)component;
                    var val = new GenericField2dVector3.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 76:
                {
                    var orig = (GenericFieldString0)component;
                    var val = new GenericFieldString0.Interop();

                    var pinnedname = orig.name != null ? Encoding.UTF8.GetBytes(orig.name) : null; fixed (void* pinnedPtrname = pinnedname) { val.name = new ByteArray { Data = pinnedPtrname, Length =  pinnedname?.Length ?? 0 };

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 77:
                {
                    var orig = (GenericFieldString1)component;
                    var val = new GenericFieldString1.Interop();

                    var pinnedname = orig.name != null ? Encoding.UTF8.GetBytes(orig.name) : null; fixed (void* pinnedPtrname = pinnedname) { val.name = new ByteArray { Data = pinnedPtrname, Length =  pinnedname?.Length ?? 0 };

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 78:
                {
                    var orig = (GenericFieldString2)component;
                    var val = new GenericFieldString2.Interop();

                    var pinnedname = orig.name != null ? Encoding.UTF8.GetBytes(orig.name) : null; fixed (void* pinnedPtrname = pinnedname) { val.name = new ByteArray { Data = pinnedPtrname, Length =  pinnedname?.Length ?? 0 };

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 79:
                {
                    var orig = (GenericFieldString3)component;
                    var val = new GenericFieldString3.Interop();

                    var pinnedname = orig.name != null ? Encoding.UTF8.GetBytes(orig.name) : null; fixed (void* pinnedPtrname = pinnedname) { val.name = new ByteArray { Data = pinnedPtrname, Length =  pinnedname?.Length ?? 0 };

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 80:
                {
                    var orig = (GenericFieldString4)component;
                    var val = new GenericFieldString4.Interop();

                    var pinnedname = orig.name != null ? Encoding.UTF8.GetBytes(orig.name) : null; fixed (void* pinnedPtrname = pinnedname) { val.name = new ByteArray { Data = pinnedPtrname, Length =  pinnedname?.Length ?? 0 };

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 81:
                {
                    var orig = (GenericFieldQuaternion0)component;
                    var val = new GenericFieldQuaternion0.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 82:
                {
                    var orig = (GenericFieldEntity0)component;
                    var val = new GenericFieldEntity0.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 83:
                {
                    var orig = (GenericFieldEntity1)component;
                    var val = new GenericFieldEntity1.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 84:
                {
                    var orig = (GenericFieldEntity2)component;
                    var val = new GenericFieldEntity2.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 85:
                {
                    var orig = (GenericFieldEntity3)component;
                    var val = new GenericFieldEntity3.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 86:
                {
                    var orig = (GenericFieldEntity4)component;
                    var val = new GenericFieldEntity4.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 87:
                {
                    var orig = (GenericFieldEntity5)component;
                    var val = new GenericFieldEntity5.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 88:
                {
                    var orig = (GenericFieldEntity6)component;
                    var val = new GenericFieldEntity6.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 89:
                {
                    var orig = (GenericFieldEntity7)component;
                    var val = new GenericFieldEntity7.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 90:
                {
                    var orig = (GenericFieldEntity8)component;
                    var val = new GenericFieldEntity8.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 91:
                {
                    var orig = (GenericFieldEntity9)component;
                    var val = new GenericFieldEntity9.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 92:
                {
                    var orig = (GenericFieldBytes0)component;
                    var val = new GenericFieldBytes0.Interop();

                    fixed (void* pinnedPtrbytes = orig.bytes) { val.bytes = new ByteArray { Data = pinnedPtrbytes, Length =  orig.bytes?.Length ?? 0 };

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 93:
                {
                    var orig = (GenericFieldByte0)component;
                    var val = new GenericFieldByte0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 94:
                {
                    var orig = (GenericFieldByte1)component;
                    var val = new GenericFieldByte1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 95:
                {
                    var orig = (GenericFieldByte2)component;
                    var val = new GenericFieldByte2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 96:
                {
                    var orig = (GenericFieldByte3)component;
                    var val = new GenericFieldByte3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 97:
                {
                    var orig = (GenericFieldByte4)component;
                    var val = new GenericFieldByte4.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 98:
                {
                    var orig = (GenericFieldByte5)component;
                    var val = new GenericFieldByte5.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 99:
                {
                    var orig = (GenericFieldByte6)component;
                    var val = new GenericFieldByte6.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 100:
                {
                    var orig = (GenericFieldByte7)component;
                    var val = new GenericFieldByte7.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 101:
                {
                    var orig = (GenericFieldByte8)component;
                    var val = new GenericFieldByte8.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 102:
                {
                    var orig = (GenericFieldByte9)component;
                    var val = new GenericFieldByte9.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 103:
                {
                    var orig = (GenericFieldSByte0)component;
                    var val = new GenericFieldSByte0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 104:
                {
                    var orig = (GenericFieldSByte1)component;
                    var val = new GenericFieldSByte1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 105:
                {
                    var orig = (GenericFieldSByte2)component;
                    var val = new GenericFieldSByte2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 106:
                {
                    var orig = (GenericFieldSByte3)component;
                    var val = new GenericFieldSByte3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 107:
                {
                    var orig = (GenericFieldSByte4)component;
                    var val = new GenericFieldSByte4.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 108:
                {
                    var orig = (GenericFieldSByte5)component;
                    var val = new GenericFieldSByte5.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 109:
                {
                    var orig = (GenericFieldSByte6)component;
                    var val = new GenericFieldSByte6.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 110:
                {
                    var orig = (GenericFieldSByte7)component;
                    var val = new GenericFieldSByte7.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 111:
                {
                    var orig = (GenericFieldSByte8)component;
                    var val = new GenericFieldSByte8.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 112:
                {
                    var orig = (GenericFieldSByte9)component;
                    var val = new GenericFieldSByte9.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 113:
                {
                    var orig = (GenericFieldShort0)component;
                    var val = new GenericFieldShort0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 114:
                {
                    var orig = (GenericFieldShort1)component;
                    var val = new GenericFieldShort1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 115:
                {
                    var orig = (GenericFieldShort2)component;
                    var val = new GenericFieldShort2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 116:
                {
                    var orig = (GenericFieldShort3)component;
                    var val = new GenericFieldShort3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 117:
                {
                    var orig = (GenericFieldShort4)component;
                    var val = new GenericFieldShort4.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 118:
                {
                    var orig = (GenericFieldShort5)component;
                    var val = new GenericFieldShort5.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 119:
                {
                    var orig = (GenericFieldShort6)component;
                    var val = new GenericFieldShort6.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 120:
                {
                    var orig = (GenericFieldShort7)component;
                    var val = new GenericFieldShort7.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 121:
                {
                    var orig = (GenericFieldShort8)component;
                    var val = new GenericFieldShort8.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 122:
                {
                    var orig = (GenericFieldShort9)component;
                    var val = new GenericFieldShort9.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 123:
                {
                    var orig = (GenericFieldUShort0)component;
                    var val = new GenericFieldUShort0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 124:
                {
                    var orig = (GenericFieldUShort1)component;
                    var val = new GenericFieldUShort1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 125:
                {
                    var orig = (GenericFieldUShort2)component;
                    var val = new GenericFieldUShort2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 126:
                {
                    var orig = (GenericFieldUShort3)component;
                    var val = new GenericFieldUShort3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 127:
                {
                    var orig = (GenericFieldUShort4)component;
                    var val = new GenericFieldUShort4.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 128:
                {
                    var orig = (GenericFieldUShort5)component;
                    var val = new GenericFieldUShort5.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 129:
                {
                    var orig = (GenericFieldUShort6)component;
                    var val = new GenericFieldUShort6.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 130:
                {
                    var orig = (GenericFieldUShort7)component;
                    var val = new GenericFieldUShort7.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 131:
                {
                    var orig = (GenericFieldUShort8)component;
                    var val = new GenericFieldUShort8.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 132:
                {
                    var orig = (GenericFieldUShort9)component;
                    var val = new GenericFieldUShort9.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 2, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 133:
                {
                    var orig = (GenericFieldChar0)component;
                    var val = new GenericFieldChar0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 134:
                {
                    var orig = (GenericFieldChar1)component;
                    var val = new GenericFieldChar1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 135:
                {
                    var orig = (GenericFieldChar2)component;
                    var val = new GenericFieldChar2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 136:
                {
                    var orig = (GenericFieldChar3)component;
                    var val = new GenericFieldChar3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 137:
                {
                    var orig = (GenericFieldChar4)component;
                    var val = new GenericFieldChar4.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 138:
                {
                    var orig = (GenericFieldChar5)component;
                    var val = new GenericFieldChar5.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 139:
                {
                    var orig = (GenericFieldChar6)component;
                    var val = new GenericFieldChar6.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 140:
                {
                    var orig = (GenericFieldChar7)component;
                    var val = new GenericFieldChar7.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 141:
                {
                    var orig = (GenericFieldChar8)component;
                    var val = new GenericFieldChar8.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 142:
                {
                    var orig = (GenericFieldChar9)component;
                    var val = new GenericFieldChar9.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 143:
                {
                    var orig = (GenericFieldLong0)component;
                    var val = new GenericFieldLong0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 144:
                {
                    var orig = (GenericFieldLong1)component;
                    var val = new GenericFieldLong1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 145:
                {
                    var orig = (GenericFieldLong2)component;
                    var val = new GenericFieldLong2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 146:
                {
                    var orig = (GenericFieldLong3)component;
                    var val = new GenericFieldLong3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 147:
                {
                    var orig = (GenericFieldULong0)component;
                    var val = new GenericFieldULong0.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 148:
                {
                    var orig = (GenericFieldULong1)component;
                    var val = new GenericFieldULong1.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 149:
                {
                    var orig = (GenericFieldULong2)component;
                    var val = new GenericFieldULong2.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 150:
                {
                    var orig = (GenericFieldULong3)component;
                    var val = new GenericFieldULong3.Interop();

                    val.number = orig.number;

                    core.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 151:
                {
                    var orig = (GenericFieldColor0)component;
                    var val = new GenericFieldColor0.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 152:
                {
                    var orig = (GenericFieldColor1)component;
                    var val = new GenericFieldColor1.Interop();

                    val.value = orig.value;

                    core.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
            }

            throw new NotImplementedException($"Failed to update a component with type {componentType}.");
        }

        public unsafe IEntityCommand GetCommand(UInt32 type, IntPtr data, Int32 dataSize)
        {
            switch (type)
            {
                  case 0: return AuthorityRequest.FromInterop(data, dataSize);
                  case 1: return AuthorityTransfer.FromInterop(data, dataSize);
                  case 2: return QuerySynced.FromInterop(data, dataSize);
                  case 3: return AdoptOrphan.FromInterop(data, dataSize);
                  case 4: return PersistenceReady.FromInterop(data, dataSize);
                  case 5: return SceneIndexChanged.FromInterop(data, dataSize);
                  case 6: return GenericCommand.FromInterop(data, dataSize);
                  case 7: return _911e6564da2362b43abf8a4fc001d8f5_c4d1bb29347d4d0d9bcf3284d827ea79.FromInterop(data, dataSize);
            }

            throw new ArgumentException($"Unkown command type {type}", nameof(type));
        }

        public unsafe IEntityInput GetInput(UInt32 type, IntPtr data, Int32 dataSize)
        {
            throw new ArgumentException($"Unknown input type {type}", nameof(type));
        }

        public unsafe bool SendCommand(CoherenceCore core, InteropEntity entity, MessageTarget target, IEntityCommand command)
        {
            var type = command.GetComponentType();
            switch (type)
            {
                case 0:
                {
                    var orig = (AuthorityRequest)command;
                    var val = new AuthorityRequest.Interop();

                    val.requester = orig.requester;
                    val.authorityType = orig.authorityType;

                    return core.SendCommand(entity, target, type, val, 8);

                }

                case 1:
                {
                    var orig = (AuthorityTransfer)command;
                    var val = new AuthorityTransfer.Interop();

                    val.newAuthority = orig.newAuthority;
                    val.accepted = orig.accepted ? (System.Byte)1 : (System.Byte)0;
                    val.authorityType = orig.authorityType;

                    return core.SendCommand(entity, target, type, val, 9);

                }

                case 2:
                {
                    var orig = (QuerySynced)command;
                    var val = new QuerySynced.Interop();

                    val.liveQuerySynced = orig.liveQuerySynced ? (System.Byte)1 : (System.Byte)0;
                    val.globalQuerySynced = orig.globalQuerySynced ? (System.Byte)1 : (System.Byte)0;

                    return core.SendCommand(entity, target, type, val, 2);

                }

                case 3:
                {
                    var orig = (AdoptOrphan)command;
                    var val = new AdoptOrphan.Interop();


                    return core.SendCommand(entity, target, type, val, 0);

                }

                case 4:
                {
                    var orig = (PersistenceReady)command;
                    var val = new PersistenceReady.Interop();


                    return core.SendCommand(entity, target, type, val, 0);

                }

                case 5:
                {
                    var orig = (SceneIndexChanged)command;
                    var val = new SceneIndexChanged.Interop();

                    val.sceneIndex = orig.sceneIndex;

                    return core.SendCommand(entity, target, type, val, 4);

                }

                case 6:
                {
                    var orig = (GenericCommand)command;
                    var val = new GenericCommand.Interop();

                    var pinnedname = orig.name != null ? Encoding.UTF8.GetBytes(orig.name) : null; fixed (void* pinnedPtrname = pinnedname) { val.name = new ByteArray { Data = pinnedPtrname, Length =  pinnedname?.Length ?? 0 };
                    fixed (void* pinnedPtrcommandData = orig.commandData) { val.commandData = new ByteArray { Data = pinnedPtrcommandData, Length =  orig.commandData?.Length ?? 0 };
                    val.entityParam1 = orig.entityParam1;
                    val.entityParam2 = orig.entityParam2;
                    val.entityParam3 = orig.entityParam3;
                    val.entityParam4 = orig.entityParam4;

                    return core.SendCommand(entity, target, type, val, 48);

}}                }

                case 7:
                {
                    var orig = (_911e6564da2362b43abf8a4fc001d8f5_c4d1bb29347d4d0d9bcf3284d827ea79)command;
                    var val = new _911e6564da2362b43abf8a4fc001d8f5_c4d1bb29347d4d0d9bcf3284d827ea79.Interop();

                    val.clientId = orig.clientId;
                    val.worldPosition = orig.worldPosition;

                    return core.SendCommand(entity, target, type, val, 16);

                }

            }

            throw new NotImplementedException($"Failed to send a command with type {type}.");
        }

        public unsafe void SendInput(CoherenceCore core, InteropEntity entity, long frame, IEntityInput input)
        {
            var type = input.GetComponentType();

            throw new NotImplementedException($"Failed to send an input with type {type}.");
        }
    }


}